// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using PsiOffice.SessionAPI.Model.Context;

#nullable disable

namespace PsiOffice.SessionAPI.Migrations
{
    [DbContext(typeof(MySQLContext))]
    partial class MySQLContextModelSnapshot : ModelSnapshot
    {
        protected override void BuildModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "8.0.3")
                .HasAnnotation("Relational:MaxIdentifierLength", 64);

            MySqlModelBuilderExtensions.AutoIncrementColumns(modelBuilder);

            modelBuilder.Entity("PsiOffice.SessionAPI.Model.Session", b =>
                {
                    b.Property<long>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bigint")
                        .HasColumnName("id");

                    MySqlPropertyBuilderExtensions.UseMySqlIdentityColumn(b.Property<long>("Id"));

                    b.Property<string>("AdditionalFilds")
                        .HasColumnType("json")
                        .HasColumnName("additional_fields");

                    b.Property<DateTime>("DtCreation")
                        .HasColumnType("datetime(6)")
                        .HasColumnName("dt_creation");

                    b.Property<DateTime>("FullDate")
                        .HasColumnType("datetime(6)")
                        .HasColumnName("full_date");

                    b.Property<long>("IdSessionType")
                        .HasColumnType("bigint")
                        .HasColumnName("id_session_type");

                    b.Property<long>("IdTreatment")
                        .HasColumnType("bigint")
                        .HasColumnName("id_treatment");

                    b.Property<bool>("IsRemote")
                        .HasColumnType("tinyint(1)")
                        .HasColumnName("is_remote");

                    b.Property<string>("Observation")
                        .HasColumnType("longtext")
                        .HasColumnName("observation");

                    b.Property<string>("Place")
                        .HasColumnType("longtext")
                        .HasColumnName("place");

                    b.HasKey("Id");

                    b.ToTable("session");
                });
#pragma warning restore 612, 618
        }
    }
}
